[package]
name = "nexafile"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
document-model.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip.workspace = true
sha2.workspace = true
base64.workspace = true
imagesize = "0.14"
