[package]
name = "native-services"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
document-model.workspace = true
nexafile.workspace = true
office-io.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempfile.workspace = true
sha2.workspace = true
tracing.workspace = true
uuid.workspace = true
