[package]
name = "office-io"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
document-model.workspace = true
nexafile.workspace = true
serde_json.workspace = true
thiserror.workspace = true
roxmltree.workspace = true
base64.workspace = true
csv = "1.4"
uuid.workspace = true
