import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readFile, writeFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
const exec = promisify(execFile);
// Inspect the actual graph, not the cache (which can retain removed packages).
const lock = await readFile("pnpm-lock.yaml", "utf8");
if (/@univerjs-pro\//.test(lock))
  throw new Error("Forbidden Pro dependency in lockfile");
const packageManager = process.env.npm_execpath;
const result = packageManager
  ? await exec(
      process.execPath,
      [packageManager, "licenses", "list", "--json"],
      { maxBuffer: 8 * 1024 * 1024 },
    )
  : await exec("corepack", ["pnpm", "licenses", "list", "--json"], {
      maxBuffer: 8 * 1024 * 1024,
    });
const npmPackages = JSON.parse(result.stdout);
const rows = Object.entries(npmPackages).flatMap(([license, packages]) =>
  packages.flatMap((p) =>
    p.versions.map((version) => [
      p.name,
      version,
      p.name === "@univerjs/telemetry"
        ? "Apache-2.0 (source header; inert service identifier only)"
        : license,
      p.homepage ?? "",
    ]),
  ),
);
const unique = [
  ...new Map(rows.map((row) => [row[0] + "@" + row[1], row])).values(),
].sort((a, b) => a[0].localeCompare(b[0]));
const cargo = JSON.parse(
  (
    await exec(
      "cargo",
      ["metadata", "--locked", "--format-version", "1", "--all-features"],
      { maxBuffer: 32 * 1024 * 1024 },
    )
  ).stdout,
);
const crates = cargo.packages
  .filter((p) => p.source)
  .sort((a, b) =>
    `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`),
  );
const table = (entries) =>
  entries
    .map(
      (row) =>
        "| " +
        row.map((s) => String(s ?? "").replaceAll("|", "\\|")).join(" | ") +
        " |",
    )
    .join("\n");
await writeFile(
  "THIRD_PARTY_LICENSES.md",
  "# Third-party dependency notices\n\nGenerated by pnpm run licenses from the installed npm graph and locked Cargo metadata, including development tools, optional features and platform-specific crates. Not every listed package is shipped in every binary. Univer Pro is prohibited. The upstream telemetry package is an inert dependency-injection identifier with no implementation or network code; no telemetry service is registered. Original available license/notice texts are collected in [THIRD_PARTY_NOTICES.txt](THIRD_PARTY_NOTICES.txt). See [dependency investigation](docs/development/dependencies.md) for platform-library licensing and distribution requirements.\n\n## JavaScript / tooling\n\n| Package | Version | License | Source |\n| --- | --- | --- | --- |\n" +
    table(unique) +
    "\n\n## Rust crates\n\n| Crate | Version | License | Source |\n| --- | --- | --- | --- |\n" +
    table(
      crates.map((p) => [
        p.name,
        p.version,
        p.license ?? "See included license file",
        p.repository ?? `https://crates.io/crates/${p.name}`,
      ]),
    ) +
    "\n",
);
const notices = [];
const absent = [];
async function collect(label, directory, extra = []) {
  const names = (await readdir(directory)).filter((name) =>
    /^(licen[cs]e|copying|notice)([._-]|$)/i.test(name),
  );
  const paths = [
    ...new Set([...names.map((name) => join(directory, name)), ...extra]),
  ];
  let found = false;
  for (const path of paths) {
    const text = await readFile(path, "utf8").catch(() => undefined);
    if (!text) continue;
    notices.push(
      `\n${"=".repeat(72)}\n${label} — ${path.slice(directory.length + 1)}\n${"=".repeat(72)}\n${text}\n`,
    );
    found = true;
  }
  if (!found) absent.push(label);
}
const seen = new Set();
for (const group of Object.values(npmPackages)) {
  for (const p of group)
    for (const path of p.paths) {
      const manifest = JSON.parse(
        await readFile(join(path, "package.json"), "utf8"),
      );
      const label = `${manifest.name}@${manifest.version}`;
      if (seen.has(label)) continue;
      seen.add(label);
      await collect(label, path);
    }
}
for (const p of crates)
  await collect(
    `${p.name}@${p.version}`,
    dirname(p.manifest_path),
    p.license_file ? [resolve(dirname(p.manifest_path), p.license_file)] : [],
  );
await writeFile(
  "THIRD_PARTY_NOTICES.txt",
  "Nexa Office — third-party license and notice texts\nGenerated from locked dependencies. Includes development/optional dependencies.\nOS libraries bundled by AppImage require a separate per-artifact platform inventory.\n\nPackages without a root license/notice file (consult their source; this is not a clearance claim):\n" +
    absent.sort().join("\n") +
    "\n" +
    notices.join(""),
);
console.log(
  `Wrote ${unique.length} npm and ${crates.length} Rust inventory entries, ${notices.length} notice texts; OSS-only check passed. ${absent.length} packages lack a root notice file.`,
);
